buy/urls.py
# -*- coding: utf-8 -*-
from subprocess import check_output
hostname = check_output('hostname').strip()
is_development = (hostname == 'Rocker' or hostname == 'rck-thinkpad')

if is_development:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.defaults import patterns, include
from buy.ads.views import ad_show, news_all_show, news_show, \
                          ad_add, ad_edit, ad_archive, cabinet, my_ads_list,\
                          reg, adverts_list
from django.contrib.auth.views import login, logout
from postman import urls as postman_urls
from buy.ads.feeds import BaseFeed, VkontakteFeed
from django.views.generic.simple import redirect_to

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', adverts_list, {'sell_page_num': '1', 'buy_page_num': '1', 
                           'cat_num': '0'}),
    (r'^list/(?P<sell_page_num>\d+)-(?P<buy_page_num>\d+)-(?P<cat_num>\d+)',
     adverts_list),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^feed/', BaseFeed()),
    (r'^feed_vkontakte/', VkontakteFeed()),
    (r'^login/$', login),
    (r'^logout/$', logout),
    (r'^item/(?P<num>\d+)/$', ad_show),
    (r'^ads/(?P<num>\d+)/$', redirect_to, {'url': '/item/%(num)s/'}),
    (r'^edit/(?P<num>\d+)/$', ad_edit),
    (r'^archive/(?P<num>\d+)/$', ad_archive),
    (r'^news/$', news_all_show),
    (r'^news/(?P<num>\d+)/$', news_show),
    (r'^add/$', ad_add),
    (r'^cabinet/$', cabinet),
    (r'^cabinet/item$', my_ads_list),
    #(r'^cabinet/msg$', msg_list),
    (r'^cabinet/msg/', include(postman_urls)),
    (r'^reg/$', reg),
    #(r'^search/$', search),
    (r'^search/', include('haystack.urls')),
)

if is_development:
    urlpatterns += staticfiles_urlpatterns()

buy/ads/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Advert(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)
    text = models.TextField()
    category = models.ForeignKey(Category)
    #image_main = models.ImageField(upload_to=".", null=True, blank=True)
    #images = models.ManyToManyField(Image, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    price = models.CharField(null=True, blank=True, max_length=32)
    place = models.CharField(null=True, blank=True, max_length=128)
    #start_price = models.IntegerField(null=True, blank=True)
    is_selled = models.BooleanField()
    #is_auction = models.BooleanField()
    sell = models.BooleanField()

    def __unicode__(self):
        return self.name

#class Bet(models.Model):
    #price = models.IntegerField()
    #date = models.DateTimeField(auto_now_add=True)
    #user = models.ForeignKey(User)
    #advert = models.ForeignKey(Advert)

    #def __unicode__(self):
        #return '%s %s' % (self.advert, self.price)


class Comment(models.Model):
    advert = models.ForeignKey(Advert)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    text = models.TextField()

    def __unicode__(self):
        return u"comment %s %s" % (self.user, self.advert)


class PrivateMessage(models.Model):
    user_from = models.ForeignKey(User, related_name='user_from')
    user_to = models.ForeignKey(User, related_name='user_to')
    created = models.DateField(auto_now_add=True)
    text = models.TextField()
    unread = models.BooleanField()

    def __unicode__(self):
        return 'from %s to %s' % (self.user_from, self.user_to)


class News(models.Model):
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)
    name = models.CharField(max_length=100)
    text = models.TextField()

    def __unicode__(self):
        return self.name


class NewsComment(models.Model):
    news = models.ForeignKey(News)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    text = models.TextField()

    def __unicode__(self):
        return 'comment %s %s' % (self.user, self.advert)


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    fullname = models.CharField(max_length=128, blank=True)
    info = models.TextField()

    def __unicode__(self):
        return '%s profile' % (self.user.username)

buy/ads/forms.py
# -*- coding: utf-8 -*-
from django import forms
from buy.ads.models import Category
from django.forms.util import ErrorList
from django.contrib.auth.models import User
from re import match


class SimpleSearchForm(forms.Form):
    category = forms.ChoiceField(label="")
    text = forms.CharField(label="")

    def __init__(self, *args, **kwargs):
        super(SimpleSearchForm, self).__init__(*args, **kwargs)
        cat_list = [(cat.id, cat.name) for cat in
                  Category.objects.all().order_by('name')]
        self.fields['category'].choices = cat_list


class CommentForm(forms.Form):
    text = forms.CharField(
                widget=forms.Textarea(attrs={'rows': 3, 
                                             'class': 'input-xlarge'}),
                label='Комменть сюда')


class AddForm(forms.Form):
    name = forms.CharField(label="Название", max_length=100,
                           widget=forms.TextInput(attrs={'size': 55}))

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name.strip()) == 0:
            self._errors['name'] = ErrorList([u"Тема не может быть пустой!"])
        return name.strip()
    text = forms.CharField(
                widget=forms.Textarea(attrs={'class': 'input-xlarge'}),
                label="Описание", required=False)
    sell_or_buy = forms.ChoiceField()
    category = forms.ChoiceField(label="Категория")
    price = forms.CharField(label="Цена", required=False, max_length=32)
    place = forms.CharField(label="Место", required=False, max_length=128)
    #image_main = forms.FileField(label="Рисунок")

    def __init__(self, *args, **kwargs):
        super(AddForm, self).__init__(*args, **kwargs)
        cat_list = [(cat.id, cat.name) for cat in
                    Category.objects.all().order_by('id')]
        self.fields['category'].choices = cat_list
        self.fields['sell_or_buy'].choices = [(0, 'Продать'), (1, 'Купить')]


class PassChangeForm(forms.Form):
    old_pass = forms.CharField(label="Старый пароль",
                               widget=forms.PasswordInput())
    new_pass = forms.CharField(label="Новый пароль",
                               widget=forms.PasswordInput())
    renew_pass = forms.CharField(label="Повторите пароль",
                                 widget=forms.PasswordInput())

    def clean_new_pass(self):
        passw = self.cleaned_data['new_pass']
        if len(passw) < 5:
            raise forms.ValidationError("Пароль должен быть длиннее 4 символов")
        return passw

    def clean(self):
        cleaned_data = self.cleaned_data
        new_pass = cleaned_data.get('new_pass')
        renew_pass = cleaned_data.get('renew_pass')
        
        if new_pass and renew_pass and new_pass != renew_pass:
            msg = u"Пароли не совпадают."
            self._errors['new_pass'] = ErrorList([msg])
            self._errors['renew_pass'] = ErrorList([msg])
            del cleaned_data['new_pass']
            del cleaned_data['renew_pass']
    
        return cleaned_data

class RegForm(forms.Form):
    username = forms.CharField(label='Имя пользователя', max_length=16)
    passw = forms.CharField(label='Пароль', max_length=64, 
                            widget = forms.PasswordInput())
    passw_again = forms.CharField(label='Пароль еще раз', max_length=64, 
                                  widget = forms.PasswordInput())
    fullname = forms.CharField(label='Полное имя', max_length=128, 
                               required=False)
    email = forms.EmailField(label='E-mail адрес')
    info = forms.CharField(label='Дополнительная информация (контакты)',
                           widget=forms.Textarea(), required=False)
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(User.objects.filter(username=username)) != 0:
            self._errors['username'] = \
                ErrorList(["Такое имя пользователя уже занято"])
        # Check if username consists of letters, numbers, underscores and 
        # whitespaces.
        if len(username) != 0 and username[0].isspace() \
                and username[-1].isspace():
            self._errors['username'] = \
                ErrorList(["Имя пользователя не должно начинаться или "
                           "заканчиваться пробелом"])
        if "  " in username:
            self._errors['username'] = \
            ErrorList(['В имени пользователя не должно быть подряд двух ' 
                       'пробелов'])
        match_object = match("[\w ]+", username)
        if (match_object and match_object.group(0) != username) \
                or not match_object:
            self._errors['username'] = \
                ErrorList(["Имя пользователя должно состоять из букв, цифр, "
                           "знаков подчеркивания и пробелов"])
        return username


    def clean_passw(self):
        passwd = self.cleaned_data['passw']
        if len(passwd) < 5:
            self._errors['passw'] = \
                ErrorList(["Пароль должен быть длиннее 4 символов"])
        return passwd

    def clean(self):
        cleaned_data = self.cleaned_data
        passwd = passwd_again = None
        if 'passw' in cleaned_data.keys() \
                and 'passw_again' in cleaned_data.keys():
            passwd = cleaned_data['passw']
            passwd_again = cleaned_data['passw_again']
        else:
            self._errors['passw'] = \
                ErrorList(["Пароль должен быть длиннее 4 символов"])
        if passwd and passwd_again and passwd != passwd_again:
            msg = u"Пароли не совпадают."
            self._errors['passw'] = ErrorList([msg])
            self._errors['passw_again'] = ErrorList([msg])
            
            del cleaned_data['passw']
            del cleaned_data['passw_again']
        
        return cleaned_data

buy/templates/ad_add.html
{% extends "main.html" %}

{% block center %}
{% if preview %}
<div align='center'>
  <div class="alert" align="center">
  <strong>Это всего лишь предпросмотр!</strong>
  </div>
  <font style='font-size:125%'><b>[{{ ad.category }}] {{ad.name}}</font></b><br>
  Сообщение было послано: {{ad.user}}
</div>
    <br><br>
    {% load bbcode %}
    {{ad.text|bbcode}}<br><br>
    {% if ad.price %}
    <b>Цена:</b> {{ad.price}}<hr>
    {% endif %}
    {% if ad.place %}
    <b>Место:</b> {{ad.place}}<hr>
    {% endif %}
    <hr><br>
{% endif %}

<div class="hidden-phone" align="center">
    <h4>Подсказка по bbCode</h4></br>
	<table class="table table-bordered table-striped">
	  <tr>
	    <td>[b]полужирный текст[/b]</td>
	    <td><strong>полужирный текст</strong></td>
	  <tr>
	  <tr>
	    <td>[i]наклонный текст[/i]</td>
	    <td><i>наклонный текст</i></td>
	  <tr>
	  <tr>
	    <td>[img]http://example.org/logo.png[/img] или<br>
	        [pic]http://example.org/logo.png[/pic]</td>
	    <td>Картинка.<br>
	        Рекомендуем хостинг катринок <a href="http://i.zlowiki.ru/" target="_blank">http://i.zlowiki.ru/</a></td>
	  <tr>
	  <tr>
	    <td>[url=http://wikipedia.org]Википедия[/url] или [url]http://ru.wikipedia.org[/url]</td>
	    <td><a href="http://wikipedia.org" target="_blank">Википедия</a> или <a href="http://ru.wikipedia.org" target="_blank">http://ru.wikipedia.org</a></td>
	  <tr>
	</table>
	<a href="http://ru.wikipedia.org/wiki/BbCode" target="_blank">подробнее о тегах...</a>
</div>

</br>
<div class="row-fluid">
	<div class="span2 visible-desktop">
	</div>
	<div class="span10">
	  <form class="form-horizontal" action="." method="post">{% csrf_token %}
	    <fieldset>
	      <div class="control-group">
            <label class="control-label" for="id_category">Купить или продать?</label>
            <div class="controls">
              {{addform.sell_or_buy}}
            </div>
          </div>
	      <div class="control-group">
	        <label class="control-label" for="id_category">Категория</label>
	        <div class="controls">
	          {{addform.category}}
	        </div>
	      </div>
	      <div class="control-group {% if addform.name.errors %}error{% endif %}">
	        <label class="control-label" for="id_name">Заголовок объявления</label>
	        <div class="controls">
	          {{addform.name}}
	          {% if addform.name.errors %}
	            <span class="help-inline">
	              {% for error in addform.name.errors %}
	                {{ error|escape }}
	              {% endfor %}
	            </span>
	          {% endif %}
	        </div>
	      </div>
	      <div class="control-group">
	        <label class="control-label" for="id_text">Текст объявления</label>
	        <div class="controls">
	          {{addform.text}}
	        </div>
	      </div>
	      <div class="control-group">
	        <label class="control-label" for="id_price">Цена (не обязательно)</label>
	        <div class="controls">
	          {{addform.price}}
	        </div>
	      </div>
	      <div class="control-group">
	        <label class="control-label" for="id_place">Место (не обязательно)</label>
	        <div class="controls">
	          {{addform.place}}
	        </div>
	      </div>
	      <div class="form-actions">
	        <button class="btn" name="preview" type="submit" {% if not user.is_authenticated %}disabled{% endif %}><i class="icon-eye-open"></i> Предварительный просмотр</button>  
	        <button class="btn" name="post" type="submit" {% if not user.is_authenticated %}disabled{% endif %}>{% if not ad_edit %}<i class="icon-plus"></i> Добавить{% else %}<i class="icon-pencil"></i> Сохранить изменения{% endif %}</button>
	      </div>
	    </fieldset>
	  </form>
	</div>
</div>
{%endblock %}

buy/templates/autocomplete_postman_multiple.html
{% extends "autocomplete.html" %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		multiple: true,
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% endblock %}

buy/templates/autocomplete_postman_single.html
{% extends "autocomplete.html" %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% endblock %}

buy/templates/cabinet.html
{% extends "main.html" %}

{% block content %}
  <ul class="nav nav-tabs">
    <li {% ifequal section "profile" %} class="active" {% endifequal %}>
      <a href="/cabinet"><i class="icon-user"></i> Профиль</a>
    </li>
    <li {% ifequal section "my_ads" %} class="active" {% endifequal %}>
	  <a href="/cabinet/item"><i class="icon-th-list"></i> Мои объявы</a>
    </li>
    <li>
      <a href="/cabinet/msg"><i class="icon-envelope"></i> Личные сообщения{% if postman_unread_count%}<span class="badge badge-warning">{{postman_unread_count}}</span>{% endif %}</a>
    </li>
  </ul>
      
  <div class="span12 well">
    {% block info %}
      <p>Имя: {{user.get_profile.fullname}}</p>
      <p>e-mail: {{user.email}}</p>
	  <p>Контакты: {{user.get_profile.info}}</p>
	
      {% if errors %}
        {% for error in errors %}
          <p>{{error}}</p>
        {% endfor %}
      {% endif %}

	  <form action="." method="POST">{% csrf_token %}
        <ul>
          {{passform.as_ul}}
        </ul>
        <input class="btn" type="submit" value="Изменить пароль">
	  </form>
    {% endblock %}
  </div>

{%endblock %} <!-- content -->

buy/templates/main.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name='yandex-verification' content='7f8aadb7f833c47d' />
    <title>{% block title %}Барахолка Физтеха{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Unknown" >

    <!-- Styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="/static/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">

    <!-- VK js -->
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?63"></script>

    <script type="text/javascript">
      VK.init({apiId: 2817356, onlyWidgets: true});
    </script>
    <!-- /VK js -->
    {% block extrahead %}{% endblock %}
  </head>

  <body>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter19215991 = new Ya.Metrika({id:19215991,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/19215991" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Барахолка Физтеха</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li {% ifequal section 'adverts' %} class="active" {% endifequal %}>
                <a href="/"><i class="icon-th-list {% ifequal section 'adverts' %} icon-white {% else %} icon-gray {% endifequal %}"></i> Объявления</a>
              </li>
              <li {% ifequal section 'new' %} class="active" {% endifequal %}>
                <a href="/add"><i class="icon-plus {% ifequal section 'new' %} icon-white {% else %} icon-gray {% endifequal %}"></i> Добавить</a>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
          <form class="navbar-search pull-left" action="/search">
            <input type="text" name="q" class="search-query span2" placeholder="Поиск">
          </form>
          <ul class="nav pull-right">
            {% if user.is_authenticated %}
              <div class="btn-group">
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                  <i class="icon-user icon-white"></i> {{user.username}}{% if postman_unread_count%} <span class="badge badge-warning">{{postman_unread_count}}</span>{% endif %}
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- dropdown menu links -->
                  <li><a href="/cabinet"><i class="icon-wrench"></i> Настройки</a></li>
                  <li><a href="/cabinet/msg"><i class="icon-envelope"></i> Сообщения{% if postman_unread_count%} <span class="badge badge-warning">{{postman_unread_count}}</span>{% endif %}</a></li>
                  <li class="divider"></li>
                  <li><a href="/logout"><i class="icon-off"></i> Выйти</a></li>
                </ul>
              </div>
            {% else %}
              <li><a href="/login" rel="nofollow">Войти</a></li>
              <li><a href="/reg" rel="nofollow">Зарегистрироваться</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

	{% if messages %}
	  {% for message in messages %}
	    <div class="alert alert-info" align="center">
	      <a class="close" data-dismiss="alert" href="#">×</a>
	      {{ message }}
	    </div>
	  {% endfor %}
	{% endif %}
	
	{% if postman_unread_count%}
	  <div class="alert alert-warning" align="center">
	    <a class="close" data-dismiss="alert" href="#">×</a>
	    У вас есть непрочитанные личные сообщения. <a href="/cabinet/msg">Прочитать.</a>
	  </div>
	{% endif %}

    <div class="container">
      <div class="row-fluid">
      {% block content %}
        <div class="span3 hidden-phone"> <!-- categories -->
        {% block leftsidebar %}
        {% load mytags %}
          <div class="well" style="padding: 8px 0;">
            <ul class="nav nav-list">
              <li class="nav-header">
                Категории:
              </li>
              <li {% ifequal cat_num 0 %}class="active"{% endifequal %}>
                <a href="/"><i class="icon-th"></i> Все</a>
              </li>
              {% for category in category_list %}
	            <li {% ifequal cat_num category.id %}class="active"{% endifequal %}>
	                 <a href='/list/1-1-{{category.id}}'><i class="{{category.name|category_icon_class}}"></i> {{category.name}}</a>
                </li>
	          {% endfor %}
            </ul>
          </div>
          <div class="well hidden-phone" style="padding: 8px 0;">
            <ul class="nav nav-list">
              <li class="nav-header">
                Последние новости
              <li>
              {% for news in news_list %}
                <li><a href="/news/{{news.id}}">{{news.name}}</a></li>
              {% endfor %}
              <li class="divider"></li>
              <li><a href='/news'>все</a></li>
            </ul>
          </div>
          <div align="center" class="visible-desktop" style="padding: 8px 0;">
            <!-- VK Widget -->
            <div id="vk_groups"></div>
            <script type="text/javascript">
              VK.Widgets.Group("vk_groups", {mode: 0, width: "200", height: "290"}, 37842813);
            </script>
          </div>
        {% endblock %}
        </div> <!-- /categories -->
        
        <div class="span9">
        {% block center %}
        <div class="well"> <!-- sell adverts -->
          <ul class="nav nav-list" style="padding: 0;">
            <li class="nav-header"><h1>Продажа</h1> {% if sell_page_num == 1 %}П{%else%}Не п{%endif%}оследние {{sell_ads_list|length}} объявлений</li>
            <li class="divider"></li>
  	        {% for ad in sell_ads_list %}
  	          <li style="margin-bottom: 5px;">
  	            <a href='/item/{{ad.id}}'>
  	              [{{ ad.category }}] {{ad.name}} - 
  	              {% ifequal user ad.user %}
  	                <b style='color:red'>
  	              {% else %}
  	                <b style='color:darkgreen'>
  	              {% endifequal %}{{ad.user}}</b>
  	              {% if ad.comment_set.all %}
  	              <span class="badge comment_count" rel="tooltip" data-original-title="количество комментариев">
  	                <i class="icon-comment"></i> {{ad.comment_set.all|length}}
  	              </span>
  	              {% endif %}
  	               - <font style='font-size:75%'>{{ad.created|date:"j/n/Y H:i"}}</font>
  	            </a>
  	          </li>
  	        {% endfor %}
	      </ul>
          <div class="pagination" align="center">
            <ul>
              {% for page_num in sell_pages_num %}
                <li {% ifequal sell_page_num page_num %}class="active"{% endifequal %}><a href="/list/{{page_num}}-{{buy_page_num}}-{{cat_num}}">{{page_num}}</a></li>
              {% endfor %}
            </ul>
          </div>   
        </div> <!-- /sell adverts -->
        
        <div class="well"> <!-- buy adverts -->   
          <ul class="nav nav-list" style="padding: 0;">
            <li class="nav-header"><h1>Покупка</h1>{% if buy_page_num == 1 %}П{%else%}Не п{%endif%}оследние {{buy_ads_list|length}} объявлений</li>
            <li class="divider"></li>
            {% for ad in buy_ads_list %}
              <li style="margin-bottom: 5px;">
                <a href='/item/{{ad.id}}'>
                  [{{ ad.category }}] {{ad.name}} - 
                  {% ifequal user ad.user %}
                    <b style='color:red'>
                  {% else %}
                    <b style='color:darkgreen'>
                  {% endifequal %}{{ad.user}}</b>
                  {% if ad.comment_set.all %}
                  <span class="badge comment_count" rel="tooltip" data-original-title="количество комментариев">
                    <i class="icon-comment"></i> {{ad.comment_set.all|length}}
                  </span>
                  {% endif %}
                   - <font style='font-size:75%'>{{ad.created|date:"j/n/Y H:i"}}</font>
                </a>
              </li>
            {% endfor %}
          </ul>
        
          <div class="pagination" align="center">
            <ul>
              {% for page_num in buy_pages_num %}
                <li {% ifequal buy_page_num page_num %}class="active"{% endifequal %}><a href="/list/{{sell_page_num}}-{{page_num}}-{{cat_num}}">{{page_num}}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div> <!-- /buy adverts -->
        {% endblock %} <!-- endblock center -->
        </div>

      {% endblock %}
      </div>
    </div> <!-- /container -->

    <footer class="footer">
      <div class="container">
        <p align="center">С вопросами, предложениями и замечаниями пишите пользователю <a href="{% url postman_write 'Rocker' %}">Rocker</a>.</p>
      </div> <!-- /footer container -->
    </footer>

    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap-transition.js"></script>
    <script src="/static/js/bootstrap-alert.js"></script>
    <script src="/static/js/bootstrap-dropdown.js"></script>
    <script src="/static/js/bootstrap-tooltip.js"></script>
    <script src="/static/js/bootstrap-collapse.js"></script>
    {% block script %}  
      <script>
        $(function()
        { $(".comment_count").tooltip();
        });
      </script>
    {% endblock %}
  </body>
</html>